---

- name: Install dotnet prerequisites
  ansible.builtin.import_tasks:
    file: prerequisites.yml

- name: Install dotnet-sdk
  ansible.builtin.import_tasks:
    file: dotnet-sdk.yml

- name: Install dotnet shell configuration
  ansible.builtin.import_tasks:
    file: shell-config.yml
