---

- name: Remove the old .NET Core SDK 2.2
  apt:
    name: dotnet-sdk-2.2
    state: absent
    purge: yes
  become: true

- name: Remove the old .NET Core SDK 3.0
  apt:
    name: dotnet-sdk-3.0
    state: absent
    purge: yes
  become: true

- name: Install the .NET Core SDK
  apt:
    name: dotnet-sdk-3.1
    state: present
  become: true

- name: Install .NET Core runtime shell config files for zsh and bash
  copy:
    src: 'shell/'
    dest: "{{ item }}"
    mode: '0660'
    directory_mode: '0700'
  with_items:
    - '~/.dotfiles/bash/'
    - '~/.dotfiles/zsh/'
