---

- name: Remove old .NET Core SDKs
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
      - dotnet-sdk-2.1
      - dotnet-sdk-3.0
      - dotnet-sdk-3.1
  become: true

- name: Install the current dotnet LTS SDK
  apt:
    name: dotnet-sdk-5.0
    state: present
  become: true

- name: Install the current dotnet Current SDK
  apt:
    name: dotnet-sdk-6.0
    state: present
  become: true

- name: Install .NET Core runtime shell config files for zsh and bash
  copy:
    src: 'shell/'
    dest: "{{ item }}"
    mode: '0660'
    directory_mode: '0700'
  with_items:
    - '~/.dotfiles/bash/'
    - '~/.dotfiles/zsh/'
