- name: Install dotnet local install Ubuntu package depdencies
  block:
    - name: Install Ubuntu 18.04 dependencies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ca-certificates
          - libc6
          - libgcc1
          - libgssapi-krb5-2
          - libicu60
          - libssl1.1
          - libstdc++6
          - zlib1g
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"
      become: true

    - name: Install Ubuntu 20.04 dependencies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ca-certificates
          - libc6
          - libgcc-s1
          - libgssapi-krb5-2
          - libicu66
          - libssl1.1
          - libstdc++6
          - zlib1g
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
      become: true

    - name: Install Ubuntu 22.04 dependencies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ca-certificates
          - libc6
          - libgcc-s1
          - libgssapi-krb5-2
          - libicu70
          - liblttng-ust1
          - libssl3
          - libstdc++6
          - libunwind8
          - zlib1g
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      become: true

    - name: Install Ubuntu 24.04 dependencies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ca-certificates
          - libc6
          - libgcc-s1
          - libicu74
          - liblttng-ust1
          - libssl3
          - libstdc++6
          - libunwind8
          - zlib1g
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "24.04"
      become: true
  when: ansible_distribution == "Ubuntu"