---

android_studio_archive_url: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2022.2.1.19/android-studio-2022.2.1.19-linux.tar.gz
android_studio_archive_name: android-studio-2022.2.1.19-linux.tar.gz
android_studio_directory_name: android-studio-2022.2.1.19-linux
android_studio_archive_checksum: sha256:6c0b4f949237470a905fac69122ed2f13d880dcff7f4c38d537885a5f8bcbf70

android_studio_install_base_directory: "/home/{{ ansible_user_id }}/Apps/AndroidStudio"
android_studio_install_archives_directory: "/home/{{ ansible_user_id }}/Apps/AndroidStudio/archives"

