---

android_studio_archive_url: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2022.1.1.19/android-studio-2022.1.1.19-linux.tar.gz
android_studio_archive_name: android-studio-2022.1.1.19-linux.tar.gz
android_studio_directory_name: android-studio-2022.1.1.19-linux
android_studio_archive_checksum: sha256:96ec44e9ad82f3a241dbc7b3b88655e3d4f2137d784b545c3574270906a68d40

android_studio_install_base_directory: "/home/{{ ansible_user_id }}/Apps/AndroidStudio"
android_studio_install_archives_directory: "/home/{{ ansible_user_id }}/Apps/AndroidStudio/archives"

