---

- name: Uninstall old ASP.NET Core runtimes
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
      - aspnetcore-runtime-2.1
      - aspnetcore-runtime-3.0
      - aspnetcore-runtime-3.1
  become: true

- name: Install the ASP.NET Core 6.0 runtime
  apt:
    name: aspnetcore-runtime-6.0
    state: present
  become: true

- name: Install ASP.NET Core runtime shell config files for zsh and bash
  copy:
    src: 'shell/'
    dest: "{{ item }}"
    mode: '0660'
    directory_mode: '0700'
  with_items:
    - '~/.dotfiles/bash/'
    - '~/.dotfiles/zsh/'
