---

- name: Install ruby build prerequisite libraries (bionic and earlier)
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - libgdbm5
  become: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version|int <= 18

- name: Install ruby build prerequisite libraries (focal and later)
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - libgdbm6
  become: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version|int >= 19

- name: Install ruby build prerequisite libraries (all ubuntu releases)
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - autoconf
      - bison
      - build-essential
      - libssl-dev
      - libyaml-dev
      - libreadline-dev
      - zlib1g-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm-dev
      - libdb-dev
  become: true
  when:
    - ansible_distribution == 'Ubuntu'

- name: Install rbenv to ~/.rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv

- name: Ensure ~/.rbenv/plugins exists
  file:
    path: ~/.rbenv/plugins
    state: directory
    mode: '0775'

- name: Install ruby-build to ~/.rbenv/plugins
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: Install the rbenv bash config files to ~/.dotfiles/bash
  copy:
    src: 'bash/'
    dest: '~/.dotfiles/bash/'
    mode: '0660'
    directory_mode: '0700'

- name: Install the rbenv zsh config files to ~/.dotfiles/zsh
  copy:
    src: 'zsh/'
    dest: '~/.dotfiles/zsh/'
    mode: '0660'
    directory_mode: '0700'
