---

- name: Install tmux
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true

- name: Install the powerline font
  ansible.builtin.apt:
    name: fonts-powerline
    state: present
  become: true

- name: Copy tmux dotfiles to ~/.dotfiles/
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '~/.dotfiles/{{ item }}'
    mode: '0660'
  with_items:
    - tmux.conf

- name: Symlink tmux dotfiles to ~/
  ansible.builtin.file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/.{{item}}
    state: link
  with_items:
    - tmux.conf

- name: Recursively copy tmux config files to ~/.dotfiles/tmux
  ansible.builtin.copy:
    src: 'tmux'
    dest: '~/.dotfiles/'
    mode: '0660'
    directory_mode: '0700'
