---

- name: Copy ruby dotfiles to ~/.dotfiles/
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '~/.dotfiles/{{ item }}'
    mode: '0660'
  with_items:
    - rspec

- name: Symlink ruby dotfiles to ~/
  ansible.builtin.file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/.{{item}}
    state: link
  with_items:
    - rspec
