---

- name: Copy ruby dotfiles to ~/.dotfiles/
  copy:
    src: '{{ item }}'
    dest: '~/.dotfiles/{{ item }}'
    mode: '0660'
  with_items:
    - rspec

- name: Symlink ruby dotfiles to ~/
  file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/.{{item}}
    state: link
  with_items:
    - rspec
