---

- name: Install ubuntu development packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ubuntu-dev-tools
      - pbuilder
      - apt-file
      - bzr-builddeb
  become: true

- name: Copy pbuilderrc dotfile to ~/.dotfiles/
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '~/.dotfiles/{{ item }}'
    mode: '0660'
  with_items:
    - pbuilderrc

- name: Symlink pbuilderrc dotfile to ~/
  ansible.builtin.file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/.{{item}}
    state: link
  with_items:
    - pbuilderrc

- name: Install deb development config files to ~/.dotfiles/bash/deb-dev-config
  ansible.builtin.template:
    src: deb-dev-config.j2
    dest: '~/.dotfiles/bash/deb-dev-config'
    mode: '0660'
    directory_mode: '0700'

- name: Install deb development config files to ~/.dotfiles/zsh/deb-dev-config
  ansible.builtin.template:
    src: deb-dev-config.j2
    dest: '~/.dotfiles/zsh/deb-dev-config'
    mode: '0660'
    directory_mode: '0700'

- name: Create ~/.dotfiles/bazaar/`
  ansible.builtin.file:
    path: ~/.dotfiles/bazaar
    state: directory
    mode: '0700'

- name: Create bazaar.conf file
  ansible.builtin.template:
    src: bazaar.conf.j2
    dest: '~/.dotfiles/bazaar/bazaar.conf'
    mode: '0660'
    directory_mode: '0700'

- name: Bazaar requires its config directory to be a real directory
  ansible.builtin.file:
    path: ~/.bazaar
    state: directory
    mode: '0700'

- name: Symlink bazaar config file to ~/.bazaar/bazaar.conf
  ansible.builtin.file:
    src: ~/.dotfiles/bazaar/bazaar.conf
    dest: ~/.bazaar/bazaar.conf
    state: link
