---

- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: present
  become: true

- name: Install universal-ctags for vim ctag management
  ansible.builtin.apt:
    name: universal-ctags
    state: present
  become: true

- name: Install the powerline font
  ansible.builtin.apt:
    name: fonts-powerline
    state: present
  become: true

- name: Copy vim dotfiles to ~/.dotfiles/
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '~/.dotfiles/{{ item }}'
    mode: '0660'
  with_items:
    - vimrc

- name: Symlink vim dotfiles to ~/
  ansible.builtin.file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/.{{item}}
    state: link
  with_items:
    - vimrc

- name: Recursively copy vim config files to ~/.dotfiles/vim
  ansible.builtin.copy:
    src: 'vim'
    dest: '~/.dotfiles/'
    mode: '0660'
    directory_mode: '0700'

- name: Symlink vim config directory to ~/.vim
  ansible.builtin.file:
    src: ~/.dotfiles/vim
    dest: ~/.vim
    state: link

- name: Install Vundle.vim from git source
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.dotfiles/vim/bundle/Vundle.vim

- name: Install or Update the Vundle.vim packages
  ansible.builtin.command: vim +PluginInstall! +qall
