---

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: true

- name: Install gitk
  ansible.builtin.apt:
    name: gitk
    state: present
  become: true

- name: Create .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: ~/.dotfiles/gitconfig
    mode: '0660'

- name: Create .gitk
  ansible.builtin.copy:
    src: gitk
    dest: ~/.dotfiles/gitk
    mode: '0660'

- name: Symlink git dotfiles to ~/
  ansible.builtin.file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/.{{item}}
    state: link
    force: yes
  with_items:
    - gitk
    - gitconfig
