---

- name: Install visual studio code
  ansible.builtin.snap:
    name: code
    classic: yes
    channel: latest/stable
  become: true

- name: Determine if a user preference file already exists
  ansible.builtin.stat:
    path: ~/.config/Code/User/settings.json
  register: vscode_preferences

- name: Create the .config directory and ensure its permissions
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: '0700'
  when: vscode_preferences.stat.exists == false

- name: Create visual studio code config directory
  ansible.builtin.file:
    path: ~/.config/Code/
    state: directory
    mode: '0700'
  when: vscode_preferences.stat.exists == false

- name: Create the visual studio code user directory
  ansible.builtin.file:
    path: ~/.config/Code/User
    state: directory
    mode: '0770'
  when: vscode_preferences.stat.exists == false

- name: Create the default settings.json file if it doesn't already exist
  ansible.builtin.copy:
    src: settings.json
    dest: ~/.config/Code/User/settings.json
    mode: '0660'
  when: vscode_preferences.stat.exists == false
