---

- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true

- name: Create ~/.dotfiles/zsh
  ansible.builtin.file:
    path: ~/.dotfiles/zsh
    state: directory
    mode: '0700'

- name: Copy zsh dotfiles to ~/.dotfiles/
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '~/.dotfiles/{{ item }}'
    mode: '0660'
  with_items:
    - zshrc
    - zlogin

- name: Symlink zsh dotfiles to ~/
  ansible.builtin.file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/.{{item}}
    state: link
  with_items:
    - zshrc
    - zlogin

- name: Recursively copy zsh config files to ~/.dotfiles/zsh
  ansible.builtin.copy:
    src: 'zsh'
    dest: '~/.dotfiles/'
    mode: '0660'
    directory_mode: '0700'
