---

- name: Add the Microsoft production PPA via the public deb package
  apt:
    deb: "https://packages.microsoft.com/config/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/packages-microsoft-prod.deb"
  register: microsoft_ppa_install
  become: true

- name: Update the apt cache following the Microsoft PPA install
  apt:
    update_cache: yes
  when: microsoft_ppa_install.changed == true
  become: true
