---

- name: Install Slack via snap from latest/stable
  ansible.builtin.snap:
    name: slack
    channel: latest/stable
    classic: true #unforutnately slack currently requires classic confinement
  become: true
