---

- name: Determine if Mono project PPA has support for this distribution version
  set_fact:
    mono_ppa_supports_distribution_version: "{{ ansible_distribution_major_version|int < 22 }}"

- name: Determine if Mono project PPA will support i386
  set_fact:
    mono_ppa_supports_i386: "{{ ansible_distribution_major_version|int < 20 }}"

- name: Add the Mono project PPA signing key
  apt_key:
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
  become: true
  when: mono_ppa_supports_distribution_version

- name: Add the Mono Project PPA with i386 support
  apt_repository:
    repo: "deb https://download.mono-project.com/repo/ubuntu stable-{{ ansible_distribution_release }}  main"
    filename: mono-official-stable
    state: present
  become: true
  when: mono_ppa_supports_distribution_version and mono_ppa_supports_i386

- name: Add the Mono Project PPA without i386 support
  apt_repository:
    repo: "deb [arch=amd64] https://download.mono-project.com/repo/ubuntu stable-{{ ansible_distribution_release }}  main"
    filename: mono-official-stable
    state: present
  become: true
  when: mono_ppa_supports_distribution_version and not mono_ppa_supports_i386
