---

- name: Update apt packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Enable support for for HTTPS in apt
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
  become: true
