---

- name: Install tor ggp signing key support package
  ansible.builtin.apt:
    name: deb.torproject.org-keyring
    state: present
  become: true

- name: Install tor
  ansible.builtin.apt:
    name: tor
    state: present
  become: true

- name: Install torsocks
  ansible.builtin.apt:
    name: torsocks
    state: present
  become: true

- name: Install tor-geoipdb
  ansible.builtin.apt:
    name: tor-geoipdb
    state: present
  become: true

- name: Update privoxy to provide a socks5 forward to tor
  ansible.builtin.lineinfile:
    path: /etc/privoxy/config
    regexp: '^\s*forward-socks5t?\s+/\s+(localhost|127.0.0.1)\s+\w+:9050\s+\.'
    insertbefore: '^#\s+5\.3\.'
    line: 'forward-socks5t / localhost:9050 .'
    state: present
  become: true
