- name: Set up a local development laptop
  hosts: local

  pre_tasks:
  - name: Load the user configuration
    include_vars:
      dir: vars
    tags: [ always ]

  roles:
    # If we tag each rule, then we can run things with the --tags command
    #

    # Core system
    #
    - role: ansible
      tags: [ default, system, development, ansible ]
    - role: network-manager
      tags: [ default, system, network-manager ]
    - role: gpg
      tags: [ default, system, security, encryption, gpg, gnupg, pgp ]
    - role: restic
      tags: [ default, system, backup, backups, restic ]

    # Shells
    #
    - role: bash
      tags: [ default, shell, bash ]
    - role: zsh
      tags: [ default, shell, zsh ]
    - role: tmux
      tags: [ default, shell, development, tmux ]
    - role: git
      tags: [ default, development, git ]

    # Password and secret management
    - role: pass
      tags: [ default, system, security, password, encryption ]
    - role: 1password
      tags: [ password, 1password ]

    # Programming languages
    #
    - role: golang
      tags: [ golang, go, goenv ]
    - role: ruby
      tags: [ rubylang, ruby, rbenv ]
    - role: nodejs
      tags: [ nodejs ]
    - role: dotnetcore-sdk
      tags: [ development, dotnetcore, dotnetcore-sdk ]
    - role: mono-sdk
      tags: [ mono-sdk, mono ]
    - role: ubuntu-development
      tags: [ ubuntu-development ]

    # Editors
    #
    - role: vim
      tags: [ default, shell, development, vim ]
    - role: visual-studio-code
      tags: [ visual-studio-code ]
    - role: android-studio
      tags: [ android, android-studio ]
    - role: godot-engine
      tags: [ godot-engine, godot ]
    - role: unityhub
      tags: [ unity-engine, unityhub, unity ]

    # Privacy tools
    #
    - role: tor
      tags: [ privacy, security ]

    # Social tools
    #
    - role: keybase
      tags: [ security, encryption, chat, keybase ]
    - role: slack
      tags: [ chat, slack ]

    # Entertainment
    - role: spotify
      tags: [ entertainment, music, spotify ]
    - role: lutris
      tags: [ gaming, lutris ]

    # Virtualization
    - role: qemu-kvm
      tags: [ virtualization, qemu-kvm ]

    # VPNs
    - role: tailscale
      tags: [ vpn, tailscale ]
