- name: Set up a local development laptop
  hosts: local

  pre_tasks:
  - name: Load the user configuration
    include_vars:
      dir: vars
    tags: [ always ]

  roles:
    # If we tag each rule, then we can run things with the --tags command
    - role: ansible
      tags: [ system, development, ansible ]
    - role: network-manager
      tags: [ system, network-manager ]
    - role: gpg
      tags: [ system, security, encryption, gpg, gnupg, pgp ]
    - role: bash
      tags: [ shell, bash ]
    - role: zsh
      tags: [ shell, zsh ]
    - role: vim
      tags: [ shell, development, vim ]
    - role: git
      tags: [ development, git ]
    - role: tmux
      tags: [ shell, development, tmux ]
    - role: pass
      tags: [ system, security, encryption ]
    - role: ruby
      tags: [ development, ruby ]
    - role: nodejs
      tags: [ development, nodejs ]
    - role: visual-studio-code
      tags: [ development, visual-studio-code ]
    - role: dotnetcore-sdk
      tags: [ development, dotnetcore, dotnetcore-sdk ]
    - role: mono-sdk
      tags: [ development, mono ]

    - role: tor
      tags: [ privacy, security ]

    - role: keybase
      tags: [ security, encryption, chat, keybase ]
    - role: slack
      tags: [ chat, slack ]

    - role: spotify
      tags: [ entertainment, music, spotify ]
