- name: Set up a local development laptop
  hosts: local

  pre_tasks:
  - name: Load the user configuration
    include_vars:
      dir: vars

  roles:
    # If we tag each rule, then we can run things with the --tags command
    - role: ansible
      tags: [ system, development, ansible ]
    - role: network-manager
      tags: [ system, network-manager ]
    - role: gpg
      tags: [ system, security, encryption, gpg, gnupg, pgp ]
    - role: bash
      tags: [ shell, bash ]
    - role: zsh
      tags: [ shell, zsh ]
    - role: vim
      tags: [ shell, development, vim ]
    - role: git
      tags: [ development, git ]
    - role: tmux
      tags: [ shell, development, tmux ]
    - role: ruby
      tags: [ development, ruby ]
