---

- name: Download the tailscale gpg package signing key
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg"
    dest: "/usr/share/keyrings/tailscale-archive-keyring.gpg"
    checksum: "sha256:3e03dacf222698c60b8e2f990b809ca1b3e104de127767864284e6c228f1fb39"
  become: true

- name: Remove the legacy oneline format tailscale apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    filename: tailscale
    state: absent
    update_cache: false
  become: true

- name: Add the deb822 format tailscale apt repository
  ansible.builtin.deb822_repository:
    name: tailscale
    types: deb
    uris: "https://pkgs.tailscale.com/stable/ubuntu"
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: "/usr/share/keyrings/tailscale-archive-keyring.gpg"
  become: true

- name: Force an apt-get update to grab the new package info
  ansible.builtin.apt:
    update_cache: yes
  become: true
