---
- name: Ensure the user specific App directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0700'
    state: directory
  with_items:
    - ~/Apps/
    - ~/Apps/bin

- name: Create the unity application directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0700'
    state: directory
  with_items:
    - ~/Apps/Unity
    - ~/Apps/Unity/Editors
    - ~/.config/UnityHub

- name: Download the Unity Hub AppImage
  ansible.builtin.get_url:
    url: https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
    dest: ~/Apps/Unity/UnityHub.AppImage
    checksum: sha256:ead7a7d2be510368e1be10314cfe8ae468b75fa8116a60291c42614fce231de8
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0700'

- name: Check to see if the UnityHub configuration directory already exists
  ansible.builtin.stat:
    path: ~/.config/UnityHub
  register: unityhub_config_dir

- name: Create the UnityHub configuration
  ansible.builtin.template:
    src: "config/UnityHub/{{ item }}.j2"
    dest: "~/.config/UnityHub/{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0600'
  with_items:
    - secondaryInstallPath.json

- name: Link the unity hub binary to the application bin directory
  ansible.builtin.file:
    src: ~/Apps/Unity/UnityHub.AppImage
    dest: ~/Apps/bin/UnityHub
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: link

- name: Check to see if the UnityHub icon has already been fetched
  ansible.builtin.stat:
    path: ~/Apps/Unity/unityhub.png
  register: unityhub_appicon

- name: Extract the UnityHub app image to get the app icon
  ansible.builtin.command:
    cmd: ./UnityHub.AppImage --appimage-extract
    chdir: ~/Apps/Unity
  when: unityhub_appicon.stat.exists == false

- name: Copy the application icon
  ansible.builtin.copy:
    src: ~/Apps/Unity/squashfs-root/usr/share/icons/hicolor/48x48/apps/unityhub.png
    dest: ~/Apps/Unity/unityhub.png
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0600'
  when: unityhub_appicon.stat.exists == false

- name: Clean up the extracted application if it exists
  ansible.builtin.file:
    path: ~/Apps/Unity/squashfs-root
    state: absent

- name: Create the applications share directory if it doesn't exist
  ansible.builtin.file:
    path: '~/.local/share/applications'
    state: directory

- name: Add UnityHub to the application launcher
  ansible.builtin.template:
    src: "local/share/applications/{{ item }}.j2"
    dest: "~/.local/share/applications/{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0600'
  with_items:
    - UnityHub.desktop
